export const HUGO_FRONT_MATTER_KEYS = [
  "title",
  "slug",
  "description",
  "summary",
  "date",
  "lastmod",
  "draft",
  "publishDate",
  "expiryDate",
  "authors",
  "tags",
  "categories",
  "keywords",
  "aliases",
  "weight",
  "layout",
  "type",
  "url",
  "linkTitle",
  "resources",
  "cascade",
  "headless",
] as const;

export const HUGO_SHORTCODES = [
  "figure",
  "gist",
  "highlight",
  "instagram",
  "param",
  "ref",
  "relref",
  "tweet",
  "vimeo",
  "x",
  "youtube",
] as const;

export const HUGO_TEMPLATE_BLOCK_KEYWORDS = [
  "if",
  "else",
  "with",
  "range",
  "define",
  "block",
  "template",
  "partial",
  "partialCached",
  "end",
] as const;

export const HUGO_TEMPLATE_FUNCTIONS = [
  "eq",
  "ne",
  "lt",
  "le",
  "gt",
  "ge",
  "and",
  "or",
  "not",
  "in",
  "isset",
  "compare.Eq",
  "compare.Ne",
  "compare.Lt",
  "compare.Le",
  "compare.Gt",
  "compare.Ge",
  "dict",
  "slice",
  "append",
  "uniq",
  "merge",
  "union",
  "intersect",
  "symdiff",
  "complement",
  "shuffle",
  "seq",
  "collections.Append",
  "collections.Dictionary",
  "collections.First",
  "collections.Last",
  "collections.After",
  "collections.Delimit",
  "collections.Group",
  "collections.In",
  "collections.Index",
  "collections.IsSet",
  "collections.Last",
  "collections.Merge",
  "collections.NewScratch",
  "collections.Querify",
  "collections.Reverse",
  "collections.Seq",
  "collections.Shuffle",
  "collections.Slice",
  "collections.Sort",
  "collections.SymDiff",
  "collections.Uniq",
  "collections.Union",
  "collections.Where",
  "printf",
  "print",
  "println",
  "warnf",
  "errorf",
  "index",
  "len",
  "default",
  "cond",
  "compare.Default",
  "safeHTML",
  "safeHTMLAttr",
  "safeCSS",
  "safeJS",
  "safeJSStr",
  "safeURL",
  "markdownify",
  "plainify",
  "htmlEscape",
  "htmlUnescape",
  "delimit",
  "where",
  "sort",
  "first",
  "last",
  "after",
  "findRE",
  "findRESubmatch",
  "replace",
  "replaceRE",
  "split",
  "strings.Contains",
  "strings.Count",
  "strings.FindRE",
  "strings.FindRESubmatch",
  "strings.HasPrefix",
  "strings.HasSuffix",
  "strings.Repeat",
  "strings.Replace",
  "strings.ReplaceRE",
  "strings.RuneCount",
  "strings.Split",
  "strings.Substr",
  "strings.ToLower",
  "strings.ToUpper",
  "strings.Trim",
  "strings.TrimLeft",
  "strings.TrimPrefix",
  "strings.TrimRight",
  "strings.TrimSpace",
  "strings.TrimSuffix",
  "lower",
  "upper",
  "title",
  "trim",
  "substr",
  "chomp",
  "truncate",
  "anchorize",
  "humanize",
  "urlize",
  "base64Decode",
  "base64Encode",
  "jsonify",
  "transform.CanEmojify",
  "transform.Emojify",
  "transform.Highlight",
  "transform.HTMLUnescape",
  "transform.Markdownify",
  "transform.Plainify",
  "transform.Remarshal",
  "transform.Unmarshal",
  "time",
  "time.AsTime",
  "time.Format",
  "time.Now",
  "dateFormat",
  "now",
  "math.Abs",
  "math.Add",
  "math.Ceil",
  "math.Div",
  "math.Floor",
  "math.Max",
  "math.Min",
  "math.Mod",
  "math.Mul",
  "math.Pow",
  "math.Round",
  "math.Sqrt",
  "math.Sub",
  "cast.ToString",
  "cast.ToInt",
  "cast.ToFloat",
  "cast.ToBool",
  "cast.ToTime",
  "path.Base",
  "path.Clean",
  "path.Dir",
  "path.Ext",
  "path.Join",
  "path.Split",
  "urls.AbsLangURL",
  "urls.AbsURL",
  "urls.Anchorize",
  "urls.JoinPath",
  "urls.Parse",
  "urls.Ref",
  "urls.RelLangURL",
  "urls.RelRef",
  "urls.RelURL",
  "resources.ExecuteAsTemplate",
  "resources.FromString",
  "resources.Get",
  "resources.GetMatch",
  "resources.Match",
  "resources.Minify",
  "resources.PostCSS",
  "resources.ToCSS",
  "resources.Concat",
  "resources.Copy",
  "resources.Fingerprint",
  "resources.Minify",
  "resources.PostProcess",
  "resources.Resize",
  "resources.Fill",
  "resources.Fit",
  "resources.Filter",
  "apply",
  "partial",
  "partialCached",
  "querify",
  "reflect.IsMap",
  "reflect.IsSlice",
  "reflect.IsString",
] as const;

export const HUGO_TEMPLATE_OBJECTS = [
  ".",
  "$",
  "site",
  "hugo",
  ".Site",
  ".Page",
  ".Params",
  ".Title",
  ".Content",
  ".Summary",
  ".RelPermalink",
  ".Permalink",
  ".Section",
  ".Kind",
  ".Type",
  ".File",
  ".Resources",
  ".Scratch",
  ".Data",
  ".Pages",
  ".RegularPages",
  ".Translations",
  ".CurrentSection",
  ".FirstSection",
  ".Parent",
  ".Ancestors",
  ".Prev",
  ".Next",
  ".PrevInSection",
  ".NextInSection",
  ".IsHome",
  ".IsNode",
  ".IsPage",
  ".IsSection",
  ".Language",
  ".Languages",
  ".Sites",
  ".TableOfContents",
  ".WordCount",
  ".ReadingTime",
  ".Draft",
  ".PublishDate",
  ".Lastmod",
  ".Date",
  ".ExpiryDate",
  ".AlternativeOutputFormats",
  ".Aliases",
  ".AllPages",
  ".AllTranslations",
  ".BaseURL",
  ".BuildDrafts",
  ".BundleType",
  ".Children",
  ".CodeOwners",
  ".Config",
  ".ContentWithoutSummary",
  ".Copyright",
  ".Description",
  ".Dimension",
  ".First",
  ".Fragments",
  ".FuzzyWordCount",
  ".GitInfo",
  ".HasChildren",
  ".Home",
  ".Identifier",
  ".IsDefault",
  ".KeyName",
  ".Keywords",
  ".LanguagePrefix",
  ".Last",
  ".Layout",
  ".Len",
  ".LinkTitle",
  ".MainSections",
  ".MediaType",
  ".Menu",
  ".Menus",
  ".Meta",
  ".Name",
  ".NumberOfElements",
  ".PageGroups",
  ".PageNumber",
  ".PageRef",
  ".PagerSize",
  ".Pagers",
  ".Path",
  ".Plain",
  ".PlainWords",
  ".Post",
  ".Pre",
  ".RawContent",
  ".RegularPagesRecursive",
  ".Rel",
  ".ResourceType",
  ".Role",
  ".Sitemap",
  ".Slug",
  ".Store",
  ".Taxonomies",
  ".TotalNumberOfElements",
  ".TotalPages",
  ".TranslationKey",
  ".Truncated",
  ".URL",
  ".Version",
  ".Weight",
  ".Width",
  ".Height",
  ".Colors",
  ".Exif",
  ".GetPage",
  ".Param",
  ".Render",
  ".Paginate",
  ".OutputFormats",
] as const;

export const HUGO_TEMPLATE_METHODS = [
  ".Scratch.Get",
  ".Scratch.Set",
  ".Scratch.Add",
  ".Scratch.Delete",
  ".Scratch.SetInMap",
  ".Scratch.DeleteInMap",
  ".Scratch.GetSortedMapValues",
  ".Resources.Get",
  ".Resources.GetMatch",
  ".Resources.Match",
  ".Resources.ByType",
  ".Resources.Mount",
  ".OutputFormats.Get",
  ".GetTerms",
  ".Ancestors.Reverse",
  ".Paginate.Pages",
  ".Eq",
  ".HasMenuCurrent",
  ".HasShortcode",
  ".HeadingsFiltered",
  ".InSection",
  ".IsAncestor",
  ".IsDescendant",
  ".IsMenuCurrent",
  ".Ref",
  ".RelRef",
  ".RenderShortcodes",
  ".RenderString",
  ".Paginator",
  ".ByDate",
  ".ByExpiryDate",
  ".ByLanguage",
  ".ByLastmod",
  ".ByLength",
  ".ByLinkTitle",
  ".ByParam",
  ".ByPublishDate",
  ".ByTitle",
  ".ByWeight",
  ".GroupBy",
  ".GroupByDate",
  ".GroupByExpiryDate",
  ".GroupByLastmod",
  ".GroupByParam",
  ".GroupByParamDate",
  ".GroupByPublishDate",
  ".Limit",
  ".Related",
  ".Reverse",
  ".Crop",
  ".Fill",
  ".Filter",
  ".Fit",
  ".Process",
  ".Publish",
  ".Resize",
  ".Get",
  ".Page",
] as const;

export const HUGO_SHORTCODE_TEMPLATE_OBJECTS = [
  ".Inner",
  ".InnerDeindent",
  ".IsNamedParams",
  ".Name",
  ".Ordinal",
  ".Page",
  ".Parent",
  ".Position",
  ".Params",
  ".Scratch",
  ".Site",
  ".Store",
] as const;

export const HUGO_SHORTCODE_TEMPLATE_METHODS = [
  ".Get",
  ".Ref",
  ".RelRef",
] as const;

export const FRONT_MATTER_KEY_TYPES: Record<string, string[]> = {
  title: ["string"],
  slug: ["string"],
  description: ["string"],
  summary: ["string"],
  date: ["string"],
  lastmod: ["string"],
  draft: ["boolean"],
  publishDate: ["string"],
  expiryDate: ["string"],
  authors: ["array", "string"],
  tags: ["array", "string"],
  categories: ["array", "string"],
  keywords: ["array", "string"],
  aliases: ["array", "string"],
  weight: ["number"],
  layout: ["string"],
  type: ["string"],
  url: ["string"],
  linkTitle: ["string"],
  resources: ["array", "object"],
  cascade: ["array", "object"],
  headless: ["boolean"],
};
