export const HUGO_FRONT_MATTER_KEYS = [
  "title",
  "slug",
  "description",
  "summary",
  "date",
  "lastmod",
  "draft",
  "publishDate",
  "expiryDate",
  "authors",
  "tags",
  "categories",
  "keywords",
  "aliases",
  "weight",
  "layout",
  "type",
  "url",
  "linkTitle",
  "resources",
  "cascade",
  "headless",
] as const;

export const HUGO_SHORTCODES = [
  "figure",
  "gist",
  "highlight",
  "instagram",
  "param",
  "ref",
  "relref",
  "tweet",
  "vimeo",
  "x",
  "youtube",
] as const;

export const FRONT_MATTER_KEY_TYPES: Record<string, string[]> = {
  title: ["string"],
  slug: ["string"],
  description: ["string"],
  summary: ["string"],
  date: ["string"],
  lastmod: ["string"],
  draft: ["boolean"],
  publishDate: ["string"],
  expiryDate: ["string"],
  authors: ["array", "string"],
  tags: ["array", "string"],
  categories: ["array", "string"],
  keywords: ["array", "string"],
  aliases: ["array", "string"],
  weight: ["number"],
  layout: ["string"],
  type: ["string"],
  url: ["string"],
  linkTitle: ["string"],
  resources: ["array", "object"],
  cascade: ["array", "object"],
  headless: ["boolean"],
};
